Test with latest setuptools and zc.buildout.
In `tox.ini` we were restricting `setuptools < 69` because 70+ gave problems last year.
Those problems have been fixed.  Now we hit a problem in buildout with that old setuptools version:

```
$ tox -e py312
py312: commands_pre[0]> .tox/py312/bin/buildout -nc /Users/maurits/community/plone-coredev/6.2/src/Products.GenericSetup/buildout.cfg buildout:directory=/Users/maurits/community/plone-coredev/6.2/src/Products.GenericSetup/.tox/py312 buildout:develop=/Users/maurits/community/plone-coredev/6.2/src/Products.GenericSetup install test
While:
  Installing.
  Checking for upgrades.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/6.2/src/Products.GenericSetup/.tox/py312/lib/python3.12/site-packages/zc/buildout/buildout.py", line 2309, in main
    getattr(buildout, command)(args)
  File "/Users/maurits/community/plone-coredev/6.2/src/Products.GenericSetup/.tox/py312/lib/python3.12/site-packages/zc/buildout/buildout.py", line 717, in install
    self._maybe_upgrade()
  File "/Users/maurits/community/plone-coredev/6.2/src/Products.GenericSetup/.tox/py312/lib/python3.12/site-packages/zc/buildout/buildout.py", line 1165, in _maybe_upgrade
    if not inspect.getfile(sys.modules[project]).startswith(dist.location):
                                                            ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'location'
```

This is something that may be fixable in `zc.buildout`.
But the easiest fix is to use setuptools 75.8.2 (or a future version).